import { ApiClientError } from '@rokdajob/shared';

/**
 * Build-time tolerance for an API that cannot answer.
 *
 * `generateStaticParams`, the sitemap and the prerender of every static page all run
 * during `next build`, on a machine that may have no route to the API at all — a CI
 * runner, a Vercel builder, or a deploy that happens while the backend is down. None of
 * that should turn into a failed deploy: the app fetches the same data at request time
 * anyway, which is exactly what it does for every record created after the build.
 *
 * The tolerance is deliberately narrow:
 *
 *  - only `ApiClientError` is caught, so a genuine bug in our own mapping code still
 *    fails the build instead of shipping a quietly empty page;
 *  - `buildFallback` only applies while the production build is running, so an outage at
 *    request time still surfaces as an error rather than an empty screen.
 */

/** True only inside `next build`. Next sets the phase for us; serving does not. */
export function isBuildPhase(): boolean {
  return process.env.NEXT_PHASE === 'phase-production-build';
}

function warn(what: string, error: ApiClientError): void {
  console.warn(`[build] ${what} is unavailable (${error.message}) — continuing without it.`);
}

/**
 * Params for a prerendered route, or none when the API cannot answer.
 *
 * With no params Next prerenders nothing for the route and renders it on first request
 * instead, because `dynamicParams` is on by default. The page is identical; only the
 * timing of its first render changes.
 */
export async function staticParams<T>(what: string, load: () => Promise<T[]>): Promise<T[]> {
  try {
    return await load();
  } catch (error) {
    if (!(error instanceof ApiClientError)) throw error;
    warn(what, error);
    return [];
  }
}

/**
 * Runs a read that the build depends on, falling back when the API cannot answer *during
 * the build*.
 *
 * The page is still prerendered, so it goes out empty and is regenerated by ISR on the
 * first request after the deploy — every read here revalidates between 30s and an hour.
 */
export async function buildFallback<T>(
  what: string,
  load: () => Promise<T>,
  fallback: T,
): Promise<T> {
  try {
    return await load();
  } catch (error) {
    if (!isBuildPhase() || !(error instanceof ApiClientError)) throw error;
    warn(what, error);
    return fallback;
  }
}
